name: Deploy to Azure App Service (Native Node.js)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: WiseBond
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run type checking
      run: npm run check
    
    - name: Build application
      run: npm run build
    
    - name: Remove dev dependencies and create deployment package
      run: |
        # Remove dev dependencies
        npm prune --production
        # Remove unnecessary files for deployment
        rm -rf .git
        rm -rf node_modules/.cache
        rm -rf coverage
        rm -rf .nyc_output
        # Keep only essential files
        find . -name "*.test.js" -delete
        find . -name "*.spec.js" -delete
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .